import {
  ClientReferral,
  Facility,
  BedRecord,
  DashboardStats,
  ActivityItem,
} from './types'

export const dashboardStats: DashboardStats = {
  totalReferrals: 156,
  pendingReferrals: 23,
  placedThisWeek: 8,
  totalBedsAvailable: 47,
  totalBeds: 312,
  occupancyRate: 85,
  avgPlacementTime: '2.4 days',
  waitlistedClients: 14,
}

export const facilities: Facility[] = [
  {
    id: 'f1',
    name: 'Hope Haven Shelter',
    type: 'emergency_shelter',
    totalBeds: 80,
    availableBeds: 12,
    reservedBeds: 3,
    maintenanceBeds: 2,
    occupiedBeds: 63,
    address: '420 Main St',
    phone: '(555) 234-5678',
    acceptingReferrals: true,
    specializations: ['Families', 'Veterans'],
  },
  {
    id: 'f2',
    name: 'New Beginnings Center',
    type: 'transitional',
    totalBeds: 45,
    availableBeds: 7,
    reservedBeds: 2,
    maintenanceBeds: 1,
    occupiedBeds: 35,
    address: '789 Oak Ave',
    phone: '(555) 345-6789',
    acceptingReferrals: true,
    specializations: ['Women', 'Substance Recovery'],
  },
  {
    id: 'f3',
    name: 'Cornerstone Housing',
    type: 'permanent_supportive',
    totalBeds: 120,
    availableBeds: 15,
    reservedBeds: 4,
    maintenanceBeds: 3,
    occupiedBeds: 98,
    address: '156 Elm Blvd',
    phone: '(555) 456-7890',
    acceptingReferrals: true,
    specializations: ['Chronic Homelessness', 'Disabilities'],
  },
  {
    id: 'f4',
    name: 'SafeSpace Haven',
    type: 'safe_haven',
    totalBeds: 30,
    availableBeds: 5,
    reservedBeds: 1,
    maintenanceBeds: 0,
    occupiedBeds: 24,
    address: '88 River Rd',
    phone: '(555) 567-8901',
    acceptingReferrals: false,
    specializations: ['Mental Health', 'Youth'],
  },
  {
    id: 'f5',
    name: 'Bridge to Home Program',
    type: 'rapid_rehousing',
    totalBeds: 37,
    availableBeds: 8,
    reservedBeds: 2,
    maintenanceBeds: 1,
    occupiedBeds: 26,
    address: '302 Pine St',
    phone: '(555) 678-9012',
    acceptingReferrals: true,
    specializations: ['Families', 'Employment Support'],
  },
]

export const referrals: ClientReferral[] = [
  {
    id: 'r1',
    clientName: 'James Carter',
    clientId: 'CL-1042',
    age: 34,
    gender: 'Male',
    referredBy: 'Maria Lopez (Outreach)',
    referredFrom: 'Street Outreach Team',
    status: 'new',
    urgency: 'critical',
    dateReferred: '2026-02-28',
    needs: ['Emergency Shelter', 'Medical', 'Substance Use'],
    notes: 'Found unsheltered near overpass. Needs immediate placement.',
  },
  {
    id: 'r2',
    clientName: 'Tanya Williams',
    clientId: 'CL-1038',
    age: 28,
    gender: 'Female',
    referredBy: 'Dr. Sarah Kim (ER)',
    referredFrom: 'Memorial Hospital',
    status: 'in_review',
    urgency: 'high',
    dateReferred: '2026-02-27',
    needs: ['Transitional Housing', 'Mental Health', 'Childcare'],
    notes: 'Discharged from hospital. Mother of 2, fleeing DV situation.',
  },
  {
    id: 'r3',
    clientName: 'Robert Chen',
    clientId: 'CL-1035',
    age: 52,
    gender: 'Male',
    referredBy: 'VA Office',
    referredFrom: 'Veterans Affairs',
    status: 'accepted',
    urgency: 'medium',
    dateReferred: '2026-02-25',
    assignedFacility: 'Hope Haven Shelter',
    needs: ['Veterans Services', 'Employment', 'Permanent Housing'],
  },
  {
    id: 'r4',
    clientName: 'Aaliyah Johnson',
    clientId: 'CL-1031',
    age: 19,
    gender: 'Female',
    referredBy: 'CPS Worker',
    referredFrom: 'Child Protective Services',
    status: 'placed',
    urgency: 'high',
    dateReferred: '2026-02-22',
    datePlaced: '2026-02-24',
    assignedFacility: 'New Beginnings Center',
    assignedBed: 'B-14',
    needs: ['Youth Services', 'Education', 'Counseling'],
  },
  {
    id: 'r5',
    clientName: 'Miguel Santos',
    clientId: 'CL-1028',
    age: 45,
    gender: 'Male',
    referredBy: 'Self-Referral',
    referredFrom: 'Walk-In',
    status: 'waitlisted',
    urgency: 'medium',
    dateReferred: '2026-02-21',
    needs: ['Permanent Supportive', 'Disabilities', 'Case Management'],
  },
  {
    id: 'r6',
    clientName: 'Patricia Owens',
    clientId: 'CL-1025',
    age: 61,
    gender: 'Female',
    referredBy: 'Senior Services',
    referredFrom: 'Area Agency on Aging',
    status: 'placed',
    urgency: 'high',
    dateReferred: '2026-02-19',
    datePlaced: '2026-02-20',
    assignedFacility: 'Cornerstone Housing',
    assignedBed: 'C-07',
    needs: ['Seniors', 'Medical', 'Daily Living Assistance'],
  },
  {
    id: 'r7',
    clientName: 'Devon Harris',
    clientId: 'CL-1020',
    age: 23,
    gender: 'Male',
    referredBy: 'Probation Officer',
    referredFrom: 'County Probation',
    status: 'declined',
    urgency: 'low',
    dateReferred: '2026-02-17',
    needs: ['Transitional Housing', 'Employment', 'Legal Aid'],
    notes: 'Declined - client did not meet eligibility criteria for available programs.',
  },
  {
    id: 'r8',
    clientName: 'Susan Park',
    clientId: 'CL-1015',
    age: 38,
    gender: 'Female',
    referredBy: 'School Social Worker',
    referredFrom: 'Lincoln Elementary',
    status: 'discharged',
    urgency: 'medium',
    dateReferred: '2026-02-10',
    datePlaced: '2026-02-12',
    assignedFacility: 'Bridge to Home Program',
    needs: ['Rapid Rehousing', 'Family Services', 'Employment'],
    notes: 'Successfully transitioned to permanent housing.',
  },
]

export const beds: BedRecord[] = [
  { id: 'b1', bedNumber: 'A-01', facilityId: 'f1', facilityName: 'Hope Haven Shelter', status: 'available' },
  { id: 'b2', bedNumber: 'A-02', facilityId: 'f1', facilityName: 'Hope Haven Shelter', status: 'occupied', occupantName: 'John D.', occupantId: 'CL-0998', checkInDate: '2026-02-15', expectedCheckout: '2026-03-15' },
  { id: 'b3', bedNumber: 'A-03', facilityId: 'f1', facilityName: 'Hope Haven Shelter', status: 'reserved', occupantName: 'Robert Chen', occupantId: 'CL-1035' },
  { id: 'b4', bedNumber: 'A-04', facilityId: 'f1', facilityName: 'Hope Haven Shelter', status: 'maintenance' },
  { id: 'b5', bedNumber: 'B-14', facilityId: 'f2', facilityName: 'New Beginnings Center', status: 'occupied', occupantName: 'Aaliyah J.', occupantId: 'CL-1031', checkInDate: '2026-02-24', expectedCheckout: '2026-05-24' },
  { id: 'b6', bedNumber: 'B-15', facilityId: 'f2', facilityName: 'New Beginnings Center', status: 'available' },
  { id: 'b7', bedNumber: 'C-07', facilityId: 'f3', facilityName: 'Cornerstone Housing', status: 'occupied', occupantName: 'Patricia O.', occupantId: 'CL-1025', checkInDate: '2026-02-20' },
  { id: 'b8', bedNumber: 'C-08', facilityId: 'f3', facilityName: 'Cornerstone Housing', status: 'available' },
]

export const recentActivity: ActivityItem[] = [
  { id: 'a1', type: 'referral_in', message: 'New critical referral: James Carter from Street Outreach', time: '30 min ago' },
  { id: 'a2', type: 'intake', message: 'Tanya Williams intake review started', time: '2 hours ago', facility: 'New Beginnings Center' },
  { id: 'a3', type: 'placement', message: 'Aaliyah Johnson placed in bed B-14', time: '4 hours ago', facility: 'New Beginnings Center' },
  { id: 'a4', type: 'bed_update', message: 'Bed A-04 moved to maintenance at Hope Haven', time: '6 hours ago', facility: 'Hope Haven Shelter' },
  { id: 'a5', type: 'discharge', message: 'Susan Park successfully discharged to permanent housing', time: '1 day ago', facility: 'Bridge to Home Program' },
  { id: 'a6', type: 'waitlist', message: 'Miguel Santos added to waitlist for Cornerstone Housing', time: '1 day ago', facility: 'Cornerstone Housing' },
  { id: 'a7', type: 'referral_in', message: 'New referral: Devon Harris from County Probation', time: '2 days ago' },
  { id: 'a8', type: 'placement', message: 'Patricia Owens placed in bed C-07', time: '2 days ago', facility: 'Cornerstone Housing' },
]

export const weeklyPlacementData = [
  { day: 'Mon', referrals: 5, placements: 2 },
  { day: 'Tue', referrals: 3, placements: 1 },
  { day: 'Wed', referrals: 7, placements: 3 },
  { day: 'Thu', referrals: 4, placements: 2 },
  { day: 'Fri', referrals: 6, placements: 3 },
  { day: 'Sat', referrals: 2, placements: 1 },
  { day: 'Sun', referrals: 1, placements: 0 },
]
